### ISSUE TITLE
`useSelection` should expose a function which focuses & selects a node, same as `onNodeClick`

### ISSUE THREAD

**Issue by neil-morrison44** [reaviz/reagraph#27]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I've got a storybook plugin which displays Recoil trees both in the graph & in a list, currently if the user clicks a node on the graph they get a nice zoom in focus animation to show the node - but if they click it in the list the node is selected (via `setSelections`) but the graph doesn't zoom to focus on it.

## Expected behavior

Ideally I'd like the same focusing action to occur regardless of if the user clicks the node in the graph or in the list.

Also it'd be really nice to have a way to trigger the hover effect.

Could be there's something returned by `useSelection` that'd do this already but I've not spotted it

## What is the motivation / use case for changing the behavior?

To allow the nice graph features to be used programmatically as well.

**Comment by amcdnl** [comment]
Couldn't you set the node selection to do this? I'm concerned this might get state out of whack if you use 2 different ways to focus things.

**Comment by amcdnl** [comment]
OK - I thought it did. Thats a bug then. If you want to take a stab at it, go for it. I will need to fix this soon eitherway.

**Comment by neil-morrison44** [comment]
Think you'll need to decide which of `setSelections` / `toggleSelection` / `removeSelection` / `addSelection` trigger a re-focus & if it only happens when exactly 1 node is selected - I had all of them doing it at one point for my PR but backed it out incase they were being used internally & it'd trigger a focus twice

**Comment by amcdnl** [comment]
Now that Im thinking about this, I'm realizing there might be 3 different use cases:

- Focus ( Focus a particular node but not select )
- Selection by External ( click on something outside of the graph and it select )
- Selection by System ( click on something inside the graph and it select )

There is a `centerGraph` method on the `GraphCanvas` which is the better way to handle this since the selection helper is optional and not required. If we did want to enhance this, we should put the methods there.

Let me think about this today. Feel free to post any thoughts in the meantime.

**Comment by neil-morrison44** [comment]
See https://github.com/reaviz/reagraph/pull/28#issuecomment-1186578682
